library(fredr)
library(zoo)
library(dplyr)
library(coda)
library(HDInterval)
library(MASS)
library(distributionsrd)
library(arrayhelpers)
library(openxlsx)


write.xlsx(dp.2010, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2010.xlsx')
write.xlsx(dp.2011, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2011.xlsx')
write.xlsx(dp.2012, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2012.xlsx')
write.xlsx(dp.2013, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2013.xlsx')
write.xlsx(dp.2014, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2014.xlsx')
write.xlsx(dp.2015, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2015.xlsx')
write.xlsx(dp.2016, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2016.xlsx')
write.xlsx(dp.2017, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2017.xlsx')
write.xlsx(dp.2018, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2018.xlsx')
write.xlsx(dp.2019, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2019.xlsx')
write.xlsx(dp.2021, 'C:/Users/corwi/OneDrive/Documents/Rhelp/dp2021.xlsx')